
List<String> items = ['Name is 1' , 
                      'here we come and here we go so what  ',
                      'don\'t bother',
                      'here we come and here we go so what shall we do to show this for you and me ',
                      'here we come and here we go so what shall we  so what shall we do to show this for you and me ',
                      'Name is ' , 
                      'here we come and here we go so what shall we do to show this for you and me ',
                      'don\'t bother',
                      'here we come and here  we do to show this for you and me ',
                      'here we come and here we go so what shall we do to show this for you and me here we come and here we go so what shall we do to show this for you and me ',
                      'here we come and here we go so what shall we do to show this for you and me ',
                      'here we come and here we go so what shall we  so what shall we do to show this for you and me ',
                      'Name is ' , 
                      'here we come and here we go so what shall we do to show this for you and me ',
                      'don\'t bother',
                      'Ok',
                      'but would be nice if we talk',
                      'in that case i will call you',
                      'lolz',
                      'what? ',
                      'Name is ' , 
                      'here we come and here we go so what  ',
                      'don\'t bother',
                      'is that so',
                      'ya he said he cant',
                      'this is top',
                      'came in lasstttt and here we go so what shall we do to show this for you and me ',
                      ];